import streamlit as st
from utils.functions import *
from exp_analysis import *


# Load necessary data
import pandas as pd
df = pd.read_csv('data/artwork_both_filtered.csv')
df['search'] = df['title_og'].astype(str) + str(' (') + df['name'].astype(str) + str(')')

# Set page title
st.set_page_config( page_title='FrostByte', 
                    page_icon= 'images/favicon.png', 
                    layout='wide')


# Title, Tabs, Sidebar 

st.title("KU Leuven Datathon 2023")

tab_home, tab_explore, tab_color, tab_aboutus = st.tabs(["Home", "Explore Data", "Color Palettes", "About Us"])

col1, col2, col3 = st.sidebar.columns([1,8,1])
with col1:
    st.write("")
with col2:
    st.image(call_image('logo.png'), use_column_width=True)
with col3:
    st.write("")

st.sidebar.markdown("We are Master's students at KU Leuven studying Statistics and Data Science. Learn more about us in About Us", unsafe_allow_html=True)              
st.sidebar.info("This project is created for KU Leuven's Datathon 2023. Our work can be found on [Github](https://github.com/AvyG/ColorArt_DT). More information about the Datathon can be found [here](https://kul-datathon-jobfair.netlify.app/#Datathon)", icon="🎨")


# Home tab

with tab_home:
    # Home Page
    st.title("Artist vs. AI-rtist")
    st.markdown("> The image you see on the left side is an original artwork by an artist. The image on the right side, however, is an artwork generated by AI with a prompt to paint the original artwork's title in the original artist's style. Although the prompt includes both the artist and the artwork title, some differences exist. As you refresh the homepage, a new set of artworks is presented. Some AI-generated artwork almost reproduces the original artwork, and some are distanced from the original artwork. \n \n What does influence the color palettes of AI-rtist and artist? Is there a difference between artworks generated by an AI-rtist and artist? We explore image data consisting of both AI-generated artworks and original artworks to answer these questions by focusing on colors.", unsafe_allow_html=True)

    # n pairs of images from artwork_both_filtered.csv
    n = 1
    image_list = load_image_list(n)

    # Display the images side-by-side
    with st.container():
        col1, col2 = st.columns(2)
        image1 = call_artwork(image_list[0][0]).resize((500,500))
        image2 = call_artwork(image_list[0][1])#.resize((500,500))
        col1.image(image1, use_column_width=True, caption="Original Artwork")
        col2.image(image2, use_column_width=True, caption="AI-Generated Artworks")


# Exploration Analysis tab

with tab_explore:
    create_exppage()
    

# Color Analysis tab
with tab_color:
    st.header("Original Artworks")
    options = list(df.search)
    st.markdown(''' ### Check the color palette of an artwork by an artist ''')
    search = st.selectbox("Choose an artwork by an artist (⚠️ It takes some time to run):", options = options, index =options.index( "Starry Night (Vincent Van Gogh)"))
    file = options.index(search)
    image_url = df.image_url.values[file]
    fig = plot_extraction(image_url, limit=5, crop=True)

    with st.expander("🖼  Artwork", expanded=True):
        st.write(fig)
    
    st.header("AI Artworks")
    st.markdown(''' ### Check the color palette of AI generated artwork  \n Note that the artworks are generated with a prompt to paint [the title of original artwork] in the style of [original artist's name]. ''')
    search_ai = st.selectbox("Choose a prompt (⚠️ It takes some time to run):", options = options, index =options.index( "Starry Night (Vincent Van Gogh)"))
    file_ai = options.index(search_ai)
    image_url_ai = df.url_AI.values[file_ai]
    fig_ai = plot_extraction(image_url_ai, limit=5, crop=False)

    with st.expander("🖼  Artwork", expanded=True):
        st.write(fig_ai)




# About Us tab

with tab_aboutus:
    st.header("About Us")
    st.markdown('''### Meet the members of Team FrostByte''', unsafe_allow_html=True)
    
    col1, col2, col3, col4 = st.columns(4, gap="medium")
    with col1:
        st.image(call_image('avatar_seorin.png'),  use_column_width=True)
        st.markdown ("Seorin Kim \n> seorin.kim@student.kuleuven.be ")
    with col2:
        st.image(call_image('avatar_jolien.png'),  use_column_width=True)
        st.markdown ("Jolien Covens \n> jolien.covens@student.kuleuven.be")
    with col3:
        st.image(call_image('avatar_johan.png'),  use_column_width=True)
        st.markdown ("Johan Rogiers \n> johan.rogiers@student.kuleuven.be ")
    with col4:
        st.image(call_image('avatar_avelyn.png'),  use_column_width=True)
        st.markdown ("Avelyn Fernanda García Araya \n> avelynfernanda.garciaaraya@student.kuleuven.be")
                
    
    
    
    