import pandas as pd
import streamlit as st
import time
from data import *

# Set page title
st.set_page_config( page_title='FrostByte', 
                    page_icon='🎨', 
                    layout='wide')


# Title, Tabs, Sidebar 

st.title("Datathon 2023")

tab_home, tab_explore, tab_analysis, tab_aboutus = st.tabs(["Home", "Exploratory Analysis", "Color Analysis", "About Us"])

col1, col2, col3 = st.sidebar.columns([1,8,1])
with col1:
    st.write("")
with col2:
    st.image('logo.png',  use_column_width=True)
with col3:
    st.write("")

st.sidebar.markdown(" ## AI-rtist vs. Artist")
st.sidebar.markdown("What does influence the color palettes of AI-rtist and artist? Is there difference between artworks generated by an AI-rtist and artist? We explore image data consisting of both AI-generated artworks and original artworks to answer these questions by focusing on colors."  )              
st.sidebar.info("This project is created for KU Leuven's Datathon 2023. Our work can be found on [Github](https://github.com/AvyG/ColorArt_DT).", icon="🎨")



# Home tab

with tab_home:
    # Home Page
    st.title("AI-rtist vs. Aritst")
    st.write("The aim of this project is to explore the relationships "+
            "between the most prominent colors in man-made and "+
            "AI-generated works with an specific style or artist"
            )
    
    # n pairs of images from artwork_both_filtered.csv
    n = 1
    image_list = load_image_list(n)

    # Display the images side-by-side
    with st.container():
        col1, col2 = st.columns(2)
        col1.image(call_artwork(image_list[0][0]), use_column_width=True)
        col2.image(call_artwork(image_list[0][1]), use_column_width=True)


